{
  "hash": "cf523442e17a5127fcfd5dc1b146121c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Session 6: Panel Data and Fixed Effects — Live Demo\"\nsubtitle: \"Advanced Data Science · Europa-Universität Flensburg\"\nauthor: \"Claudius Gräbner-Radkowitsch\"\ndate: \"2026-05-28\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: true\n    code-tools: true\n    self-contained: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n  execute-dir: file\n---\n\n# Setup\n\n## Business question\n\n> *Does rising income make countries happier — and what would it take to interpret that relationship causally?*\n\nThis question has a deceptively simple answer in cross-sectional data (yes, richer countries are happier) and a much less clear answer when we follow countries over time (the Easterlin paradox). Panel data methods let us be precise about which comparison we are making and what we can credibly claim.\n\n## Packages and data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::i_am(\"content/material/session06/lecture_notes.qmd\")\nlibrary(here)\nlibrary(tidyverse)\nlibrary(fixest)\nlibrary(modelsummary)\nlibrary(flextable)\nlibrary(patchwork)\n\ndat <- read_csv(\n  here(\"content/material/session06/data/happiness_income.csv\"), \n  show_col_types = FALSE)\nglimpse(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,869\nColumns: 10\n$ country      <chr> \"Afghanistan\", \"Afghanistan\", \"Afghanistan\", \"Afghanistan…\n$ iso2c        <chr> \"AF\", \"AF\", \"AF\", \"AF\", \"AF\", \"AF\", \"AF\", \"AF\", \"AF\", \"AF…\n$ iso3c        <chr> \"AFG\", \"AFG\", \"AFG\", \"AFG\", \"AFG\", \"AFG\", \"AFG\", \"AFG\", \"…\n$ year         <dbl> 2011, 2012, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 202…\n$ GDP_ppp      <dbl> 80913174278, 91231454558, 98965950295, 100402257641, 1026…\n$ population   <dbl> 29347708, 30560034, 32792523, 33831764, 34700612, 3568893…\n$ unemployment <dbl> 7.830, 7.875, 7.915, 9.032, 10.116, 11.184, 11.192, 11.18…\n$ GDP_pc       <dbl> 2757.053, 2985.319, 3017.943, 2967.692, 2958.785, 2952.99…\n$ happiness    <dbl> 4.2580, 4.0400, 3.5750, 3.3600, 3.7940, 3.6320, 3.2030, 2…\n$ gini_disp    <dbl> 31.7, 31.8, 31.9, 31.9, 31.9, 31.9, NA, NA, NA, NA, NA, N…\n```\n\n\n:::\n:::\n\n\nThe dataset merges three sources:\n\n| Variable | Source | Description |\n|---|---|---|\n| `happiness` | World Happiness Report 2026 | Life satisfaction (0–10, 3-year average) |\n| `GDP_pc` | World Bank WDI | GDP per capita, PPP (constant 2017 int'l $) |\n| `gini_disp` | SWIID 9.2 | Disposable income Gini coefficient |\n| `unemployment` | World Bank WDI | Unemployment rate (% of labour force) |\n| `population` | World Bank WDI | Total population |\n\n---\n\n# Exploring the Data\n\n## Panel structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat |>\n  summarise(\n    n_countries = n_distinct(country),\n    n_years     = n_distinct(year),\n    year_min    = min(year),\n    year_max    = max(year),\n    n_obs       = n()\n  ) |> \n  flextable() |> \n  theme_vanilla() |> \n  autofit()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-12bc9730{}.cl-12b9e526{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-12b9e530{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-12bad026{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-12bad9d6{width:1.151in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12bad9d7{width:0.863in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12bad9d8{width:0.956in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12bad9e0{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12bad9e1{width:0.735in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12bad9e2{width:1.151in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12bad9e3{width:0.863in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12bad9e4{width:0.956in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12bad9ea{width:0.99in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12bad9eb{width:0.735in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-12bc9730'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-12bad9d6\"><p class=\"cl-12bad026\"><span class=\"cl-12b9e526\">n_countries</span></p></th><th class=\"cl-12bad9d7\"><p class=\"cl-12bad026\"><span class=\"cl-12b9e526\">n_years</span></p></th><th class=\"cl-12bad9d8\"><p class=\"cl-12bad026\"><span class=\"cl-12b9e526\">year_min</span></p></th><th class=\"cl-12bad9e0\"><p class=\"cl-12bad026\"><span class=\"cl-12b9e526\">year_max</span></p></th><th class=\"cl-12bad9e1\"><p class=\"cl-12bad026\"><span class=\"cl-12b9e526\">n_obs</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12bad9e2\"><p class=\"cl-12bad026\"><span class=\"cl-12b9e530\">146</span></p></td><td class=\"cl-12bad9e3\"><p class=\"cl-12bad026\"><span class=\"cl-12b9e530\">14</span></p></td><td class=\"cl-12bad9e4\"><p class=\"cl-12bad026\"><span class=\"cl-12b9e530\">2,011</span></p></td><td class=\"cl-12bad9ea\"><p class=\"cl-12bad026\"><span class=\"cl-12b9e530\">2,025</span></p></td><td class=\"cl-12bad9eb\"><p class=\"cl-12bad026\"><span class=\"cl-12b9e530\">1,869</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat |>\n  count(country) |>\n  count(n, name = \"n_countries\") |>\n  rename(years_observed = n)|> \n  flextable() |> \n  theme_vanilla() |> \n  autofit()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-12cefb64{}.cl-12ccdb90{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-12ccdb9a{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-12cdb09c{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-12cdb9e8{width:1.449in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdb9f2{width:1.151in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdb9f3{width:1.449in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdb9f4{width:1.151in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdb9fc{width:1.449in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdb9fd{width:1.151in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdb9fe{width:1.449in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdba06{width:1.151in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdba07{width:1.449in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdba08{width:1.151in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdba10{width:1.449in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdba11{width:1.151in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdba12{width:1.449in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdba1a{width:1.151in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdba1b{width:1.449in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdba1c{width:1.151in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdba24{width:1.449in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdba25{width:1.151in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdba26{width:1.449in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-12cdba27{width:1.151in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-12cefb64'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-12cdb9e8\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb90\">years_observed</span></p></th><th class=\"cl-12cdb9f2\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb90\">n_countries</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12cdb9f3\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">1</span></p></td><td class=\"cl-12cdb9f4\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12cdb9fc\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">2</span></p></td><td class=\"cl-12cdb9fd\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12cdb9fe\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">3</span></p></td><td class=\"cl-12cdba06\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12cdb9fc\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">4</span></p></td><td class=\"cl-12cdb9fd\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12cdba07\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">5</span></p></td><td class=\"cl-12cdba08\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12cdba10\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">6</span></p></td><td class=\"cl-12cdba11\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12cdb9fc\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">7</span></p></td><td class=\"cl-12cdb9fd\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12cdba12\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">9</span></p></td><td class=\"cl-12cdba1a\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12cdba1b\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">10</span></p></td><td class=\"cl-12cdba1c\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">4</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12cdba24\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">11</span></p></td><td class=\"cl-12cdba25\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12cdb9fc\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">12</span></p></td><td class=\"cl-12cdb9fd\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12cdba10\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">13</span></p></td><td class=\"cl-12cdba11\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">6</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-12cdba26\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">14</span></p></td><td class=\"cl-12cdba27\"><p class=\"cl-12cdb09c\"><span class=\"cl-12ccdb9a\">117</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nThe panel is **unbalanced** — not every country is observed in every year. This is typical for survey-based cross-country data and causes no problems for fixed effects estimation.\n\n## Cross-country variation in happiness\n\nBefore running any regression, it helps to see the structure of the data. How much of the variation in happiness is *between* countries vs. *within* countries over time?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat |>\n  group_by(country) |>\n  summarise(\n    happiness = mean(happiness, na.rm = TRUE),\n    log_gdp   = mean(log(GDP_pc), na.rm = TRUE),\n    .groups   = \"drop\"\n  ) |>\n  filter(!is.na(happiness), !is.na(log_gdp)) |>\n  ggplot(aes(log_gdp, happiness)) +\n  geom_point(colour = \"#2C5F8A\", alpha = 0.7, size = 2) +\n  geom_smooth(method = \"lm\", colour = \"#D04A2F\", se = TRUE,\n              fill = \"#D04A2F\", alpha = 0.12, linewidth = 1) +\n  labs(\n    x = \"Log GDP per capita (PPP), country mean\",\n    y = \"Life satisfaction (0–10), country mean\"\n  ) +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Average happiness and log GDP per capita by country (full-period means). Richer countries are clearly happier in cross-section.](lecture_notes_files/figure-html/fig-country-means-1.png){#fig-country-means width=672}\n:::\n:::\n\n\nThe cross-sectional correlation is strong and positive. But is this evidence that income *causes* happiness?\n\n## Within-country trends: the Easterlin challenge\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhighlight <- c(\"United States\", \"Japan\", \"South Korea\", \"China\", \"Germany\")\n\ncol_hl <- c(\n  \"United States\" = \"#D04A2F\",\n  \"Japan\"         = \"#e67e22\",\n  \"South Korea\"   = \"#8e44ad\",\n  \"China\"         = \"#2C5F8A\",\n  \"Germany\"       = \"#4A9B6F\"\n)\n\ndat |>\n  filter(country %in% highlight, !is.na(happiness)) |>\n  ggplot(aes(year, happiness, colour = country)) +\n  geom_line(linewidth = 1.1) +\n  geom_point(size = 1.8) +\n  scale_colour_manual(values = col_hl, name = NULL) +\n  scale_x_continuous(breaks = seq(2006, 2024, by = 4)) +\n  labs(x = NULL, y = \"Life satisfaction (0–10)\",\n       caption = \"Source: World Happiness Report (3-year averages)\") +\n  theme_minimal(base_size = 13) +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![Happiness over time for selected countries. GDP per capita rose substantially in all of them — but happiness trends differ.](lecture_notes_files/figure-html/fig-within-trends-1.png){#fig-within-trends width=672}\n:::\n:::\n\n\nChina's GDP per capita roughly quadrupled over this period. Its happiness score rose modestly. The United States had strong aggregate growth — yet happiness has trended flat or downward. This is the Easterlin paradox in the data.\n\n---\n\n# The Model Progression\n\n## Step 0 — Pooled OLS: the naive baseline\n\nPool all country-year observations and regress happiness on log income, ignoring panel structure entirely.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm0 <- feols(happiness ~ log(GDP_pc), data = dat)\n\nmodelsummary(\n  list(\"Pooled OLS\" = m0),\n  coef_map  = c(\"log(GDP_pc)\" = \"Log GDP per capita\"),\n  statistic = \"conf.int\", conf_level = 0.95,\n  gof_map   = c(\"nobs\", \"r.squared\"),\n  stars     = TRUE,\n  output    = \"flextable\"\n) |> autofit()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1344506c{}.cl-1341c414{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-13429c86{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1342a596{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1342a597{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1342a5a0{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1342a5a1{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1342a5a2{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1342a5a3{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1342a5aa{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1342a5ab{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1342a5ac{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1342a5ad{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1342a5ae{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1342a5b4{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1344506c'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-1342a596\"><p class=\"cl-13429c86\"><span class=\"cl-1341c414\"> </span></p></th><th class=\"cl-1342a597\"><p class=\"cl-13429c86\"><span class=\"cl-1341c414\">Pooled OLS</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1342a5a0\"><p class=\"cl-13429c86\"><span class=\"cl-1341c414\">Log GDP per capita</span></p></td><td class=\"cl-1342a5a1\"><p class=\"cl-13429c86\"><span class=\"cl-1341c414\">0.813***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1342a5a2\"><p class=\"cl-13429c86\"><span class=\"cl-1341c414\"></span></p></td><td class=\"cl-1342a5a3\"><p class=\"cl-13429c86\"><span class=\"cl-1341c414\">[0.786, 0.840]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1342a5aa\"><p class=\"cl-13429c86\"><span class=\"cl-1341c414\">Num.Obs.</span></p></td><td class=\"cl-1342a5ab\"><p class=\"cl-13429c86\"><span class=\"cl-1341c414\">1729</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1342a5ac\"><p class=\"cl-13429c86\"><span class=\"cl-1341c414\">R2</span></p></td><td class=\"cl-1342a5ad\"><p class=\"cl-13429c86\"><span class=\"cl-1341c414\">0.672</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"2\"class=\"cl-1342a5ae\"><p class=\"cl-13429c86\"><span class=\"cl-1341c414\">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\nThe large positive coefficient is not surprising — it reflects the strong cross-sectional pattern we already saw. But it conflates between-country differences (richer country = happier country) with within-country change (rising income → rising happiness). The former is dominated by stable country characteristics that we have not controlled for.\n\n## The composite error — why pooled OLS is biased\n\nThe pooled OLS error $\\epsilon_{it}$ has two components:\n\n$$\\epsilon_{it} = \\eta_i + v_{it}$$\n\n- $\\eta_i$: everything stable about country $i$ that we do not observe — culture, institutions, social trust, history\n- $v_{it}$: genuine year-to-year noise\n\nIf $\\eta_i$ correlates with $\\log(\\text{GDP}_{it})$ — and it clearly does, since rich institutional environments produce both high income *and* high happiness — pooled OLS is biased. This is OVB with an unobserved variable.\n\n## Step 1 — Country fixed effects: removing stable confounders\n\nCountry FE absorbs $\\eta_i$ entirely by subtracting each country's time-mean from every variable:\n\n$$\\tilde{y}_{it} = y_{it} - \\bar{y}_i \\qquad \\tilde{x}_{it} = x_{it} - \\bar{x}_i$$\n\nBecause $\\eta_i - \\bar{\\eta}_i = 0$, the stable country component disappears. The coefficient is now identified from **within-country variation only**: when a country's income rises above its own historical average, does its happiness rise too?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- feols(happiness ~ log(GDP_pc) | country,\n            vcov = ~country,\n            data = dat)\n\nmodelsummary(\n  list(\"Country FE\" = m1),\n  coef_map  = c(\"log(GDP_pc)\" = \"Log GDP per capita\"),\n  statistic = \"conf.int\", conf_level = 0.95,\n  gof_map   = c(\"nobs\", \"r.squared\", \"r2.within\"),\n  stars     = TRUE,\n  output    = \"flextable\"\n) |> autofit()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1354f8e0{}.cl-1352e1e0{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1353bf98{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1353c876{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1353c880{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1353c881{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1353c88a{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1353c88b{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1353c894{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1353c895{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1353c896{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1353c89e{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1353c89f{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1353c8a0{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1353c8a8{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1353c8a9{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1353c8aa{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1354f8e0'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-1353c876\"><p class=\"cl-1353bf98\"><span class=\"cl-1352e1e0\"> </span></p></th><th class=\"cl-1353c880\"><p class=\"cl-1353bf98\"><span class=\"cl-1352e1e0\">Country FE</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1353c881\"><p class=\"cl-1353bf98\"><span class=\"cl-1352e1e0\">Log GDP per capita</span></p></td><td class=\"cl-1353c88a\"><p class=\"cl-1353bf98\"><span class=\"cl-1352e1e0\">1.259***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1353c88b\"><p class=\"cl-1353bf98\"><span class=\"cl-1352e1e0\"></span></p></td><td class=\"cl-1353c894\"><p class=\"cl-1353bf98\"><span class=\"cl-1352e1e0\">[0.829, 1.688]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1353c895\"><p class=\"cl-1353bf98\"><span class=\"cl-1352e1e0\">Num.Obs.</span></p></td><td class=\"cl-1353c896\"><p class=\"cl-1353bf98\"><span class=\"cl-1352e1e0\">1727</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1353c89e\"><p class=\"cl-1353bf98\"><span class=\"cl-1352e1e0\">R2</span></p></td><td class=\"cl-1353c89f\"><p class=\"cl-1353bf98\"><span class=\"cl-1352e1e0\">0.928</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1353c8a0\"><p class=\"cl-1353bf98\"><span class=\"cl-1352e1e0\">R2 Within</span></p></td><td class=\"cl-1353c8a8\"><p class=\"cl-1353bf98\"><span class=\"cl-1352e1e0\">0.150</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"2\"class=\"cl-1353c8a9\"><p class=\"cl-1353bf98\"><span class=\"cl-1352e1e0\">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\nContrary to a naive expectation, the country FE coefficient is *larger* than in pooled OLS — see the full discussion below.\n\n### Visualising the within-transformation\n\nTo build intuition, let us manually demean one slice of the data and overlay the within-country slopes on the raw scatter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwithin_dat <- dat |>\n  filter(country %in% highlight) |>\n  group_by(country) |>\n  mutate(\n    happiness_dm = happiness   - mean(happiness,    na.rm = TRUE),\n    log_gdp_dm   = log(GDP_pc) - mean(log(GDP_pc),  na.rm = TRUE)\n  ) |>\n  ungroup()\n\np_raw <- dat |>\n  filter(country %in% highlight) |>\n  ggplot(aes(log(GDP_pc), happiness)) +\n  geom_point(colour = \"grey70\", alpha = 0.4, size = 1.5) +\n  geom_smooth(method = \"lm\", colour = \"#D04A2F\", se = FALSE,\n              linewidth = 0.8, linetype = \"dashed\") +\n  geom_smooth(aes(colour = country), method = \"lm\", se = FALSE, linewidth = 1) +\n  scale_colour_manual(values = col_hl, guide = \"none\") +\n  labs(x = \"Log GDP per capita\", y = \"Happiness\",\n       title = \"Raw data\", subtitle = \"Dashed = pooled OLS\") +\n  theme_minimal(base_size = 11)\n\np_demeaned <- within_dat |>\n  ggplot(aes(log_gdp_dm, happiness_dm)) +\n  geom_point(aes(colour = country), alpha = 0.6, size = 1.5) +\n  geom_smooth(method = \"lm\", colour = \"#D04A2F\", se = FALSE, linewidth = 1) +\n  scale_colour_manual(values = col_hl, name = NULL) +\n  labs(x = \"Log GDP (demeaned)\", y = \"Happiness (demeaned)\",\n       title = \"Demeaned data\", subtitle = \"Within-country variation only\") +\n  theme_minimal(base_size = 11) +\n  theme(legend.position = \"bottom\")\n\np_raw + p_demeaned\n```\n\n::: {.cell-output-display}\n![Raw data vs. demeaned data for selected countries. The grey overall trend is dominated by between-country differences; coloured lines show within-country slopes only.](lecture_notes_files/figure-html/fig-within-slopes-1.png){#fig-within-slopes width=672}\n:::\n:::\n\n\nThe between-country slope (dashed, left panel) is steep. The within-country slope (right panel) is flatter — in some countries barely positive. This is the Easterlin paradox captured in a single figure.\n\n## Step 2 — Two-way fixed effects: controlling for global time shocks\n\nCountry FE removes stable country differences. But what about shocks that hit all countries in the same year — a global recession, a pandemic, a commodity price surge? If such shocks correlate with income changes, country-only FE is not enough.\n\n**Two-way FE** adds a separate intercept for each year:\n\n$$y_{it} = \\alpha_i + \\gamma_t + \\beta \\log(\\text{GDP}_{it}) + v_{it}$$\n\n$\\hat\\beta$ is now identified from variation that is neither explained by *which country* nor *which year*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- feols(happiness ~ log(GDP_pc) | country + year,\n            vcov = ~country,\n            data = dat)\n\nmodelsummary(\n  list(\"Two-way FE\" = m2),\n  coef_map  = c(\"log(GDP_pc)\" = \"Log GDP per capita\"),\n  statistic = \"conf.int\", conf_level = 0.95,\n  gof_map   = c(\"nobs\", \"r.squared\", \"r2.within\"),\n  stars     = TRUE,\n  output    = \"flextable\"\n) |> autofit()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1391df44{}.cl-138f941e{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1390915c{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-13909ab2{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13909ab3{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13909abc{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13909ac6{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13909ac7{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13909ac8{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13909ac9{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13909ad0{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13909ad1{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13909ad2{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13909ad3{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13909ada{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13909adb{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13909ae4{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1391df44'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-13909ab2\"><p class=\"cl-1390915c\"><span class=\"cl-138f941e\"> </span></p></th><th class=\"cl-13909ab3\"><p class=\"cl-1390915c\"><span class=\"cl-138f941e\">Two-way FE</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13909abc\"><p class=\"cl-1390915c\"><span class=\"cl-138f941e\">Log GDP per capita</span></p></td><td class=\"cl-13909ac6\"><p class=\"cl-1390915c\"><span class=\"cl-138f941e\">1.554***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13909ac7\"><p class=\"cl-1390915c\"><span class=\"cl-138f941e\"></span></p></td><td class=\"cl-13909ac8\"><p class=\"cl-1390915c\"><span class=\"cl-138f941e\">[0.943, 2.164]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13909ac9\"><p class=\"cl-1390915c\"><span class=\"cl-138f941e\">Num.Obs.</span></p></td><td class=\"cl-13909ad0\"><p class=\"cl-1390915c\"><span class=\"cl-138f941e\">1727</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13909ad1\"><p class=\"cl-1390915c\"><span class=\"cl-138f941e\">R2</span></p></td><td class=\"cl-13909ad2\"><p class=\"cl-1390915c\"><span class=\"cl-138f941e\">0.930</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13909ad3\"><p class=\"cl-1390915c\"><span class=\"cl-138f941e\">R2 Within</span></p></td><td class=\"cl-13909ada\"><p class=\"cl-1390915c\"><span class=\"cl-138f941e\">0.142</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"2\"class=\"cl-13909adb\"><p class=\"cl-1390915c\"><span class=\"cl-138f941e\">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\n## The standard progression side by side\n\n\n::: {#tbl-main-progression .cell tbl-cap='Three models of the income–happiness relationship. 95% confidence intervals in brackets. Within-R² is the relevant fit statistic for FE models.'}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"Pooled OLS\" = m0, \"Country FE\" = m1, \"Two-way FE\" = m2),\n  coef_map  = c(\"log(GDP_pc)\" = \"Log GDP per capita\"),\n  statistic = \"conf.int\", conf_level = 0.95,\n  gof_map   = c(\"nobs\", \"r.squared\", \"r2.within\"),\n  stars     = TRUE,\n  notes     = \"95% CIs in brackets. Pooled OLS: HC1 SEs. FE models: clustered at country level.\",\n  output    = \"flextable\"\n) |> autofit()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-13ba961e{}.cl-13b88658{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-13b961ea{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-13b96b04{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13b96b05{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13b96b06{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13b96b0e{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13b96b0f{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13b96b10{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13b96b11{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13b96b18{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13b96b19{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13b96b1a{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13b96b1b{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13b96b22{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13b96b23{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13b96b24{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-13ba961e'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-13b96b04\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\"> </span></p></th><th class=\"cl-13b96b05\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">Pooled OLS</span></p></th><th class=\"cl-13b96b05\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">Country FE</span></p></th><th class=\"cl-13b96b05\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">Two-way FE</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13b96b06\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">Log GDP per capita</span></p></td><td class=\"cl-13b96b0e\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">0.813***</span></p></td><td class=\"cl-13b96b0e\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">1.259***</span></p></td><td class=\"cl-13b96b0e\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">1.554***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13b96b0f\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\"></span></p></td><td class=\"cl-13b96b10\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">[0.786, 0.840]</span></p></td><td class=\"cl-13b96b10\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">[0.829, 1.688]</span></p></td><td class=\"cl-13b96b10\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">[0.943, 2.164]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13b96b11\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">Num.Obs.</span></p></td><td class=\"cl-13b96b18\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">1729</span></p></td><td class=\"cl-13b96b18\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">1727</span></p></td><td class=\"cl-13b96b18\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">1727</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13b96b19\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">R2</span></p></td><td class=\"cl-13b96b1a\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">0.672</span></p></td><td class=\"cl-13b96b1a\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">0.928</span></p></td><td class=\"cl-13b96b1a\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">0.930</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13b96b1b\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">R2 Within</span></p></td><td class=\"cl-13b96b22\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\"></span></p></td><td class=\"cl-13b96b22\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">0.150</span></p></td><td class=\"cl-13b96b22\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">0.142</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"4\"class=\"cl-13b96b23\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"4\"class=\"cl-13b96b23\"><p class=\"cl-13b961ea\"><span class=\"cl-13b88658\">95% CIs in brackets. Pooled OLS: HC1 SEs. FE models: clustered at country level.</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\n**Reading the table:**\n\n- **Pooled OLS → Country FE:** The coefficient *increases* from 0.81 to 1.26. This is counter-intuitive but real: the within-country income–happiness relationship is *stronger* than the cross-sectional comparison between countries. Countries going through active income growth (e.g. emerging markets) show larger happiness gains than the gap between a rich and a poor country at one point in time would suggest. The cross-sectional estimate is compressed partly by diminishing returns at high income levels and by stable between-country differences in happiness baselines.\n- **Country FE → Two-way FE:** The coefficient increases further to 1.55. Year FE removes global shocks that simultaneously raised incomes and happiness everywhere (good global years); after removing those, the within-country, within-year income–happiness signal is stronger.\n- **Within-R²** (0.15–0.14): income explains roughly 15–14% of within-country happiness variation — meaningful but modest. Happiness has many determinants beyond income.\n\n---\n\n# Causal Interpretation\n\n## What the FE estimate claims — and does not claim\n\nThe two-way FE coefficient answers:\n\n> When a country's income rises above its own historical average in a year that is not unusually good or bad for all countries, does its happiness tend to rise?\n\n**Country FE already controls for:**\n\n- All time-invariant country characteristics: stable institutions, culture, geography, social trust, historical development path\n- This includes most of what makes Scandinavian countries both rich *and* happy — it is absorbed into $\\alpha_i$\n\n**Year FE already controls for:**\n\n- Global shocks affecting all countries in a given year: financial crises, pandemics, commodity cycles\n\n**What is still potentially uncontrolled:**\n\nTime-varying factors that change *differently across countries* and independently affect both income and happiness. Two obvious candidates in our data: **income inequality** and **unemployment**.\n\n## Three estimands — precision about what you want to estimate\n\nBefore adding more controls, it is worth being precise about which causal quantity you are actually after.\n\n| Estimand | What you condition on | What it answers |\n|---|---|---|\n| **Total effect** of income on happiness | Nothing on the causal path | \"Does richer = happier, all channels included?\" |\n| **Controlled direct effect** (CDE) | Mediators held fixed (e.g. healthcare) | \"Does income matter *beyond* health, trust, etc.?\" |\n| **Indirect / path-specific effect** via M | Estimated via mediation analysis | \"How much of the income effect runs *through* health?\" |\n\nOur main estimate (`m2`) is an attempt at the **total within-country effect** — it includes all pathways through which rising income may raise happiness: better healthcare, reduced stress, more autonomy, improved public services, and any direct effect.\n\n## A common temptation: controlling for WHR variables\n\nThe WHR reports several variables alongside happiness: social support, healthy life expectancy, freedom to make life choices, perceptions of corruption. The temptation is to add these as controls to \"isolate the direct income effect\" or \"remove confounding.\"\n\n::: {.callout-warning}\n## This is the bad-control problem again\n\nMost of these WHR variables are **mediators**, not confounders:\n\n- Healthy life expectancy: income → health → happiness\n- Social support: income enables social networks → happiness\n- Freedom to choose: affluence enables autonomy → happiness\n\nConditioning on a mediator does two things simultaneously:\n\n1. It removes part of the income effect (blocking the mediated path)\n2. If the mediator also has independent determinants (culture, geography), it opens new backdoor paths — introducing bias rather than removing it\n\nThe result is a **controlled direct effect** that answers a different question than the total effect — and does so with additional bias from the newly opened paths. This is precisely the \"bad control\" problem from Session 5, applied at the macro level.\n:::\n\n## Stage 1 — Total effect with time-varying confounders\n\nThe appropriate additions are variables that independently affect both income and happiness *and change over time within countries*, without lying on the causal path from income to happiness.\n\n**Income inequality (`gini_disp`):** The US Easterlin story is partly about rising inequality — aggregate GDP grew, but most of the gains went to the top, so median incomes stagnated. Gini is a time-varying confounder (or effect modifier): it captures distributional changes that affect happiness independently of average income.\n\n**Unemployment (`unemployment`):** Labour market conditions affect wellbeing through channels (job security, social belonging) that are partly independent of aggregate income.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3a <- feols(happiness ~ log(GDP_pc) + gini_disp               | country + year,\n             vcov = ~country, data = dat)\n\nm3b <- feols(happiness ~ log(GDP_pc) + unemployment            | country + year,\n             vcov = ~country, data = dat)\n\nm3  <- feols(happiness ~ log(GDP_pc) + gini_disp + unemployment | country + year,\n             vcov = ~country, data = dat)\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {#tbl-confounders .cell tbl-cap='Adding time-varying confounders to the two-way FE baseline. 95% confidence intervals in brackets. Note: the sample shrinks when Gini is included (missing data).'}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\n    \"Two-way FE\"    = m2,\n    \"+ Gini\"        = m3a,\n    \"+ Unemployment\"= m3b,\n    \"+ Both\"        = m3\n  ),\n  coef_map = c(\n    \"log(GDP_pc)\"  = \"Log GDP per capita\",\n    \"gini_disp\"    = \"Gini (disposable income)\",\n    \"unemployment\" = \"Unemployment rate\"\n  ),\n  statistic = \"conf.int\", conf_level = 0.95,\n  gof_map   = c(\"nobs\", \"r.squared\", \"r2.within\"),\n  stars     = TRUE,\n  notes     = \"Two-way FE (country + year) throughout. SEs clustered at country level.\",\n  output    = \"flextable\"\n) |> autofit()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-13e830ec{}.cl-13e5d9e6{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-13e6c770{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-13e6d152{width:1.966in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d153{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d154{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d155{width:1.444in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d15c{width:1.321in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d15d{width:1.966in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d15e{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d166{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d167{width:1.444in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d168{width:1.321in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d169{width:1.966in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d170{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d171{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d172{width:1.444in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d17a{width:1.321in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d17b{width:1.966in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d17c{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d184{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d185{width:1.444in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d186{width:1.321in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d187{width:1.966in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d18e{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d18f{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d190{width:1.444in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d191{width:1.321in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d198{width:1.966in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d199{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d19a{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d19b{width:1.444in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1a2{width:1.321in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1a3{width:1.966in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1a4{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1ac{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1ad{width:1.444in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1ae{width:1.321in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1af{width:1.966in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1b6{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1b7{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1b8{width:1.444in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1c0{width:1.321in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1c1{width:1.966in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1c2{width:1.22in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1c3{width:1.27in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1e8{width:1.444in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-13e6d1e9{width:1.321in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-13e830ec'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-13e6d152\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\"> </span></p></th><th class=\"cl-13e6d153\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">Two-way FE</span></p></th><th class=\"cl-13e6d154\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">+ Gini</span></p></th><th class=\"cl-13e6d155\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">+ Unemployment</span></p></th><th class=\"cl-13e6d15c\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">+ Both</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13e6d15d\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">Log GDP per capita</span></p></td><td class=\"cl-13e6d15e\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">1.554***</span></p></td><td class=\"cl-13e6d166\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">1.740***</span></p></td><td class=\"cl-13e6d167\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">1.217***</span></p></td><td class=\"cl-13e6d168\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">1.376***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13e6d169\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\"></span></p></td><td class=\"cl-13e6d170\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">[0.943, 2.164]</span></p></td><td class=\"cl-13e6d171\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">[1.044, 2.436]</span></p></td><td class=\"cl-13e6d172\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">[0.602, 1.833]</span></p></td><td class=\"cl-13e6d17a\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">[0.666, 2.086]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13e6d17b\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">Gini (disposable income)</span></p></td><td class=\"cl-13e6d17c\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\"></span></p></td><td class=\"cl-13e6d184\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">-0.021</span></p></td><td class=\"cl-13e6d185\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\"></span></p></td><td class=\"cl-13e6d186\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">-0.026</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13e6d169\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\"></span></p></td><td class=\"cl-13e6d170\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\"></span></p></td><td class=\"cl-13e6d171\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">[-0.057, 0.016]</span></p></td><td class=\"cl-13e6d172\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\"></span></p></td><td class=\"cl-13e6d17a\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">[-0.059, 0.008]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13e6d187\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">Unemployment rate</span></p></td><td class=\"cl-13e6d18e\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\"></span></p></td><td class=\"cl-13e6d18f\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\"></span></p></td><td class=\"cl-13e6d190\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">-0.042***</span></p></td><td class=\"cl-13e6d191\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">-0.036***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13e6d169\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\"></span></p></td><td class=\"cl-13e6d170\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\"></span></p></td><td class=\"cl-13e6d171\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\"></span></p></td><td class=\"cl-13e6d172\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">[-0.061, -0.024]</span></p></td><td class=\"cl-13e6d17a\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">[-0.055, -0.017]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13e6d198\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">Num.Obs.</span></p></td><td class=\"cl-13e6d199\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">1727</span></p></td><td class=\"cl-13e6d19a\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">1308</span></p></td><td class=\"cl-13e6d19b\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">1711</span></p></td><td class=\"cl-13e6d1a2\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">1297</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13e6d1a3\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">R2</span></p></td><td class=\"cl-13e6d1a4\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">0.930</span></p></td><td class=\"cl-13e6d1ac\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">0.942</span></p></td><td class=\"cl-13e6d1ad\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">0.935</span></p></td><td class=\"cl-13e6d1ae\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">0.945</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-13e6d1af\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">R2 Within</span></p></td><td class=\"cl-13e6d1b6\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">0.142</span></p></td><td class=\"cl-13e6d1b7\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">0.156</span></p></td><td class=\"cl-13e6d1b8\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">0.186</span></p></td><td class=\"cl-13e6d1c0\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">0.194</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"5\"class=\"cl-13e6d1c1\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"5\"class=\"cl-13e6d1c1\"><p class=\"cl-13e6c770\"><span class=\"cl-13e5d9e6\">Two-way FE (country + year) throughout. SEs clustered at country level.</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\n::: {.callout-note}\n## Interpreting the results\n\nThe income coefficient remains **large and significant** throughout (1.55 → 1.38 in the full model, 95% CI well above zero). The key findings from each column:\n\n- **+ Gini only:** The Gini coefficient is negative but not statistically significant at conventional levels. The sample shrinks substantially due to missing Gini observations — results should be interpreted cautiously.\n- **+ Unemployment only:** Unemployment is negative and highly significant — higher unemployment reduces happiness within countries even after controlling for income and fixed effects. Adding unemployment leaves the income coefficient largely unchanged.\n- **+ Both:** The income coefficient falls modestly (11% relative to the baseline). Most of the action comes from unemployment, not Gini. The income–happiness relationship is robust to these time-varying controls.\n\n**A note on sample composition:** adding Gini reduces the sample by 419 observations (from 1727 to 1308). Part of the income coefficient shift when Gini is included may reflect this sample restriction rather than the Gini control itself. Compare columns (1) and (3) — the unemployment-only model uses nearly the same sample as the baseline — to isolate the cleaner comparison.\n:::\n\n## Stage 2 — Why mediation analysis, not more controls\n\nThe concern *\"maybe it is not income but good healthcare that makes people happier\"* is a question about **indirect effects**: how much of the total income–happiness relationship runs through healthcare?\n\nThat is a legitimate question — but it requires a **different estimand** than what we have been computing, and a different analytical strategy.\n\n**The wrong approach:** add healthcare (or WHR healthy life expectancy) to the main regression. As explained above, this gives the controlled direct effect, introduces mediator bias, and does not actually answer the indirect effect question.\n\n**The right approach — causal mediation decomposition:**\n\n$$\\underbrace{\\hat\\beta_{\\text{total}}}_{\\text{Total effect}} = \\underbrace{\\hat\\beta_{\\text{direct}}}_{\\text{Income → Happiness, not via M}} + \\underbrace{\\hat\\beta_{\\text{indirect}}}_{\\text{Income → M → Happiness}}$$\n\nThis requires:\n\n1. A model for the **mediator** (e.g., healthy life expectancy ~ income + country FE + year FE + confounders)\n2. A model for **happiness** including both income and the mediator\n3. Strong identification assumptions — crucially, no unmeasured confounders of the mediator–outcome relationship, which is demanding at the macro level\n\nThe practical upshot: if a mediation analysis found a large indirect effect through healthcare (i.e., most of the income effect runs through better health), that would support the view that policies improving health *without* income growth could also raise happiness — a different policy conclusion than if the income effect were mostly direct.\n\n::: {.callout-note}\n## Further reading\nThe World Happiness Report investigates mediation pathways in its statistical appendices — see the methods notes in recent editions for their approach to decomposing the cross-country happiness gaps. Note that findings on the relative importance of income vs. social variables differ across WHR editions and decomposition methods, and these are cross-sectional decompositions, not panel FE estimates.\n:::\n\n**Mediation analysis is beyond the scope of this session**, but if you pursue this line of research, the `mediation` package in R implements the Imai et al. framework for causal mediation under the sequential ignorability assumption.\n\n---\n\n# Reporting Panel Results in Quarto\n\n## What to include in every panel table\n\n\n::: {#tbl-final-quarto .cell tbl-cap='Income and happiness: pooled OLS, country FE, two-way FE, and two-way FE with time-varying controls. 95% confidence intervals in brackets. Preferred specification: column (4).'}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\n    \"(1) Pooled OLS\"      = m0,\n    \"(2) Country FE\"      = m1,\n    \"(3) Two-way FE\"      = m2,\n    \"(4) + Gini & Unemp.\" = m3\n  ),\n  coef_map  = c(\n    \"log(GDP_pc)\"  = \"Log GDP per capita\",\n    \"gini_disp\"    = \"Gini coefficient\",\n    \"unemployment\" = \"Unemployment rate\"\n  ),\n  statistic = \"conf.int\", conf_level = 0.95,\n  gof_map   = c(\"nobs\", \"r.squared\", \"r2.within\"),\n  stars     = TRUE,\n  notes     = c(\n    \"95% CIs in brackets.\",\n    \"Column (1): HC1 standard errors.\",\n    \"Columns (2)–(4): clustered at country level.\",\n    \"Country and year fixed effects in columns (3) and (4).\"\n  ),\n  output    = \"flextable\"\n) |> autofit()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1414026c{}.cl-14119806{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-141285b8{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-14129012{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129013{width:1.338in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412901c{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412901d{width:1.363in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412901e{width:1.639in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129026{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129027{width:1.338in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129028{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129029{width:1.363in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129030{width:1.639in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129031{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412903a{width:1.338in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412903b{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412903c{width:1.363in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412903d{width:1.639in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129044{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129045{width:1.338in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129046{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412904e{width:1.363in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412904f{width:1.639in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129050{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129051{width:1.338in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129058{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129059{width:1.363in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412905a{width:1.639in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412905b{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129062{width:1.338in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129063{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129064{width:1.363in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412906c{width:1.639in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412906d{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412906e{width:1.338in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129076{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129077{width:1.363in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129078{width:1.639in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129080{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129081{width:1.338in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129082{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129083{width:1.363in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412908a{width:1.639in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412908b{width:1.627in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1412908c{width:1.338in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129094{width:1.287in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129095{width:1.363in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-14129096{width:1.639in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1414026c'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-14129012\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"> </span></p></th><th class=\"cl-14129013\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">(1) Pooled OLS</span></p></th><th class=\"cl-1412901c\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">(2) Country FE</span></p></th><th class=\"cl-1412901d\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">(3) Two-way FE</span></p></th><th class=\"cl-1412901e\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">(4) + Gini &amp; Unemp.</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-14129026\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">Log GDP per capita</span></p></td><td class=\"cl-14129027\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">0.813***</span></p></td><td class=\"cl-14129028\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">1.259***</span></p></td><td class=\"cl-14129029\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">1.554***</span></p></td><td class=\"cl-14129030\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">1.376***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-14129031\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-1412903a\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">[0.786, 0.840]</span></p></td><td class=\"cl-1412903b\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">[0.829, 1.688]</span></p></td><td class=\"cl-1412903c\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">[0.943, 2.164]</span></p></td><td class=\"cl-1412903d\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">[0.666, 2.086]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-14129044\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">Gini coefficient</span></p></td><td class=\"cl-14129045\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-14129046\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-1412904e\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-1412904f\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">-0.026</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-14129031\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-1412903a\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-1412903b\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-1412903c\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-1412903d\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">[-0.059, 0.008]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-14129050\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">Unemployment rate</span></p></td><td class=\"cl-14129051\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-14129058\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-14129059\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-1412905a\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">-0.036***</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-14129031\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-1412903a\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-1412903b\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-1412903c\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-1412903d\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">[-0.055, -0.017]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1412905b\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">Num.Obs.</span></p></td><td class=\"cl-14129062\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">1729</span></p></td><td class=\"cl-14129063\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">1727</span></p></td><td class=\"cl-14129064\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">1727</span></p></td><td class=\"cl-1412906c\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">1297</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1412906d\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">R2</span></p></td><td class=\"cl-1412906e\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">0.672</span></p></td><td class=\"cl-14129076\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">0.928</span></p></td><td class=\"cl-14129077\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">0.930</span></p></td><td class=\"cl-14129078\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">0.945</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-14129080\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">R2 Within</span></p></td><td class=\"cl-14129081\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\"></span></p></td><td class=\"cl-14129082\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">0.150</span></p></td><td class=\"cl-14129083\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">0.142</span></p></td><td class=\"cl-1412908a\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">0.194</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"5\"class=\"cl-1412908b\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"5\"class=\"cl-1412908b\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">95% CIs in brackets.</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"5\"class=\"cl-1412908b\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">Column (1): HC1 standard errors.</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"5\"class=\"cl-1412908b\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">Columns (2)–(4): clustered at country level.</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"5\"class=\"cl-1412908b\"><p class=\"cl-141285b8\"><span class=\"cl-14119806\">Country and year fixed effects in columns (3) and (4).</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\n**Five rules for panel tables:**\n\n1. **Show the progression** — pooled OLS to your preferred specification. The reader needs to see what each layer of controls does.\n2. **Report CIs, not SEs** — confidence intervals communicate both precision and the range of compatible effect sizes more directly than standard errors.\n3. **Report which FEs are included** — a footnote is cleaner than coefficient rows: *\"Country and year fixed effects in columns (3) and (4).\"*\n4. **Report the within-$R^2$** — use `gof_map = c(\"nobs\", \"r.squared\", \"r2.within\")`. The overall $R^2$ is inflated by the fixed effects.\n5. **State the clustering** — always note clustering level in the table footer.\n\n## Reporting confidence intervals in `modelsummary`\n\nBy default `modelsummary` shows standard errors below point estimates. To show 95% confidence intervals instead:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"Model\" = m),\n  statistic  = \"conf.int\",   # [lower, upper] replaces (SE)\n  conf_level = 0.95\n)\n```\n:::\n\n\nTo show the estimate and CI on the same line (common in reports):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"Model\" = m),\n  estimate   = \"{estimate} [{conf.low}, {conf.high}]\",\n  statistic  = NULL           # suppress the second row entirely\n)\n```\n:::\n\n\nFor a **publication-ready flextable**, add `output = \"flextable\"` and pipe through `autofit()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"Model\" = m),\n  statistic = \"conf.int\",\n  conf_level = 0.95,\n  output    = \"flextable\"\n) |>\n  autofit()\n```\n:::\n\n\n## Writing up the result\n\nA clean analytical paragraph based on the actual results:\n\n> Table 1 shows the relationship between log GDP per capita and life satisfaction across countries and years. The pooled OLS estimate (column 1) suggests a positive association (β = 0.81, 95% CI [0.79, 0.84]), but this conflates stable between-country differences with within-country income changes. Contrary to a naive reading of the Easterlin paradox, country fixed effects (column 2) reveal a *stronger* within-country relationship (β = 1.26, 95% CI [0.83, 1.69]): countries experiencing income growth show larger happiness gains than the cross-sectional gap between rich and poor countries would predict. Adding year fixed effects (column 3) increases the coefficient further to β = 1.55 (95% CI [0.94, 2.16]), as global time trends that simultaneously affected incomes and happiness everywhere are removed. Column 4 adds time-varying controls for inequality and unemployment; the income coefficient falls modestly to β = 1.38 (95% CI [0.67, 2.09]), driven mainly by the significant negative effect of unemployment rather than by Gini (which is not significant). The evidence points to a robust, positive within-country income–happiness relationship — with unemployment emerging as an important independent determinant of within-country happiness variation.\n\n---\n\n# Summary\n\n**What we did:**\n\n1. Established the cross-sectional income–happiness correlation and the Easterlin challenge\n2. Ran the standard FE progression: pooled OLS → country FE → two-way FE\n3. Clarified what each model estimates and what confounders remain\n4. Distinguished three estimands: total effect, controlled direct effect, indirect effect\n5. Added time-varying confounders (Gini, unemployment) as Stage 1 extensions\n6. Explained why conditioning on WHR variables (health, trust) is the wrong way to address mediator concerns — and what the right way (mediation analysis) would look like\n\n**Key takeaways:**\n\n- The within-country income–happiness relationship is **stronger** than the cross-sectional comparison — the FE coefficient exceeds pooled OLS\n- Country FE eliminates all stable confounders; year FE removes common time shocks\n- Unemployment is a significant time-varying confounder; Gini is not significant in this panel (possibly due to limited within-country variation and missing data)\n- WHR social/health variables are mediators — adding them gives a controlled direct effect, not a cleaner total effect, and may introduce new bias\n- Mediation analysis is the right framework for decomposing pathways; it requires stronger assumptions and is a separate analytical step\n\n**In R:** `fixest::feols(y ~ x + controls | country + year, vcov = ~country)`\n\n---\n\n# Further Reading\n\n- Békés, G. & Kézdi, G. (2021). *Data Analysis for Business, Economics, and Policy*. Cambridge UP. Ch. 24 (Panel data).\n- Huntington-Klein, N. (2022). *The Effect*. Ch. 16 (Fixed Effects). [theeffectbook.net](https://theeffectbook.net)\n- Cunningham, S. (2021). *Causal Inference: The Mixtape*. Ch. 8 (Panel data). [mixtape.scunning.com](https://mixtape.scunning.com)\n- Pearl, J. & Mackenzie, D. (2018). *The Book of Why*. Ch. 9 (Mediation) — accessible treatment of direct vs. indirect effects\n- Imai, K., Keele, L. & Tingley, D. (2010). A general approach to causal mediation analysis. *Psychological Methods*, 15(4), 309–334 — the standard reference for the `mediation` R package\n- Killingsworth, M. A., Kahneman, D., & Mellers, B. (2023). Income and emotional well-being: A conflict resolved. Proceedings of the National Academy of Sciences, 120(10), e2208661120. https://doi.org/10.1073/pnas.2208661120\n- World Happiness Report (annual, [worldhappiness.report](https://www.worldhappiness.report/)) — statistical appendices document their approach to decomposing happiness gaps across countries\n",
    "supporting": [
      "lecture_notes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}