{
  "hash": "5e8fa9a27c9c5f981c5dc2394fc81558",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Session 3: Modelling Binary and Categorical Outcomes\"\nsubtitle: \"Session 3 · Quantitative Data Analysis\"\nauthor: \"Claudius Gräbner-Radkowitsch\"\ndate: \"2026-05-07\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: false\n    code-tools: true\n    self-contained: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n# Introduction\n\n## Business question\n\n> *Can we predict which firms are likely to exit the market in the next year?*\n\nThis question is highly relevant in business practice: investors, banks, and regulators all have an interest in understanding which firms are at risk of failure. But answering it with standard regression runs into an immediate problem — the outcome we care about, *firm exit*, is a binary variable: a firm either exits (1) or it doesn't (0).\n\nIn this session, we work through why ordinary least squares (OLS) breaks down for such outcomes, develop the intuition for logistic regression, and learn how to estimate, interpret, and communicate logistic regression results in R.\n\n## Packages and data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(modelsummary)\nlibrary(marginaleffects)\nlibrary(broom)\n```\n:::\n\n\nWe use the `bisnode-firms` dataset from the open-access textbook by Békés & Kézdi (2021). It contains 19,036 Hungarian manufacturing and services firms, observed over time. Our outcome variable is `exit`, a binary indicator equal to 1 if the firm closed in the following year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirms <- read_csv(\"data/bisnode-firms.csv\")\nglimpse(firms)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 17,506\nColumns: 11\n$ comp_id       <dbl> 1002029, 1011889, 1014183, 1018301, 1022796, 1035705, 10…\n$ exit          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,…\n$ sales_log     <dbl> 13.943477, 12.980031, 11.773208, 8.813174, 10.169549, 10…\n$ employees_log <dbl> -0.78015860, 0.48317409, -0.33508429, -1.87877086, -2.48…\n$ profit_margin <dbl> 0.008554417, 0.223101892, -0.018128871, -0.164738285, -0…\n$ age           <dbl> 6, 20, 11, 8, 11, 1, 14, 5, 2, 4, 2, 1, 2, 4, 16, 1, 23,…\n$ liquidity     <dbl> 1.69277357, 8.46944789, 24.16025018, 3.05624997, 0.90785…\n$ foreign       <dbl> 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,…\n$ female_ceo    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,…\n$ industry      <dbl> 27, 55, 55, 56, 56, 56, 29, 56, 56, 27, 41, 55, 56, 28, …\n$ urban         <dbl> 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,…\n```\n\n\n:::\n:::\n\n\nLet us first look at the outcome variable:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirms |>\n  count(exit) |>\n  mutate(share = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n   exit     n  share\n  <dbl> <int>  <dbl>\n1     0 16294 0.931 \n2     1  1212 0.0692\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\nNotice that exit events are relatively rare — this is typical of survival data and has implications for model evaluation that we will revisit in Session 9 (prediction vs. inference).\n:::\n\nA quick look at the main predictors:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirms |>\n  select(exit, sales_log, employees_log, profit_margin, age) |>\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      exit           sales_log      employees_log    profit_margin       \n Min.   :0.00000   Min.   : 1.309   Min.   :-2.485   Min.   :-1.0000000  \n 1st Qu.:0.00000   1st Qu.: 9.828   1st Qu.:-2.331   1st Qu.:-0.2542683  \n Median :0.00000   Median :10.895   Median :-1.473   Median : 0.0001222  \n Mean   :0.06923   Mean   :10.967   Mean   :-1.256   Mean   :-0.1428446  \n 3rd Qu.:0.00000   3rd Qu.:12.021   3rd Qu.:-0.626   3rd Qu.: 0.0322967  \n Max.   :1.00000   Max.   :18.478   Max.   : 5.019   Max.   : 1.0000000  \n      age        \n Min.   : 0.000  \n 1st Qu.: 3.000  \n Median : 8.000  \n Mean   : 8.991  \n 3rd Qu.:15.000  \n Max.   :34.000  \n```\n\n\n:::\n:::\n\n\n---\n\n# Why OLS Fails for Binary Outcomes\n\n## The Linear Probability Model\n\nThe simplest approach is to regress the binary outcome directly on predictors using OLS. This is called the **Linear Probability Model (LPM)**:\n\n$$\\text{exit}_i = \\beta_0 + \\beta_1 \\cdot \\text{sales\\_log}_i + \\beta_2 \\cdot \\text{profit\\_margin}_i + \\varepsilon_i$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlpm <- lm(exit ~ sales_log + profit_margin + employees_log,\n          data = firms)\nsummary(lpm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = exit ~ sales_log + profit_margin + employees_log, \n    data = firms)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.27563 -0.07935 -0.05414 -0.03527  1.04989 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    0.216657   0.022001   9.848  < 2e-16 ***\nsales_log     -0.013902   0.001729  -8.041 9.45e-16 ***\nprofit_margin -0.087885   0.005908 -14.875  < 2e-16 ***\nemployees_log  0.005976   0.002556   2.338   0.0194 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2498 on 17502 degrees of freedom\nMultiple R-squared:  0.03178,\tAdjusted R-squared:  0.03162 \nF-statistic: 191.5 on 3 and 17502 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe coefficient interpretation is straightforward: a one-unit increase in `profit_margin` is associated with a -0.088 change in the *probability* of exit.\n\n### The problem: out-of-bounds predictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlpm_fitted <- augment(lpm, data = firms)\n\nlpm_fitted |>\n  summarise(\n    min_pred = min(.fitted),\n    max_pred = max(.fitted),\n    n_below_zero = sum(.fitted < 0),\n    n_above_one  = sum(.fitted > 1)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  min_pred max_pred n_below_zero n_above_one\n     <dbl>    <dbl>        <int>       <int>\n1  -0.0651    0.277          338           0\n```\n\n\n:::\n:::\n\n\nWe have 338 predicted values below zero and 0 above one. These are mathematically impossible as probabilities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lpm_fitted, aes(x = sales_log, y = .fitted)) +\n  geom_point(alpha = 0.2, size = 0.8, color = \"#2c7bb6\") +\n  geom_hline(yintercept = c(0, 1), linetype = \"dashed\", color = \"firebrick\") +\n  annotate(\"label\", x = max(firms$sales_log, na.rm = TRUE) - 1,\n           y = -0.05, label = \"Impossible (P < 0)\",\n           color = \"firebrick\", size = 3) +\n  labs(\n    title = \"LPM: Fitted probabilities of firm exit\",\n    x = \"Log sales\", y = \"Predicted P(exit = 1)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](demo_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n### The problem: heteroskedastic errors\n\nWhen Y is binary, the variance of the error term depends on X by construction:\n\n$$\\text{Var}(\\varepsilon_i | x_i) = P_i(1 - P_i)$$\n\nThis means OLS standard errors are not valid, so hypothesis tests and confidence intervals are unreliable. We can verify this visually — the residuals should show a clear fan pattern.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(lpm_fitted, aes(x = .fitted, y = .resid)) +\n  geom_point(alpha = 0.2, size = 0.8) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  labs(title = \"LPM residuals vs. fitted values\",\n       x = \"Fitted value\", y = \"Residual\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](demo_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-warning}\nDespite these problems, the LPM is widely used in economics, especially with panel data. It can serve as a useful benchmark. But you should always be aware of its limitations.\n:::\n\n---\n\n# Logistic Regression: Intuition\n\n## The logistic function\n\nWe need a function that maps any real number to a probability in [0, 1]. The **logistic (sigmoid) function** does exactly this:\n\n$$\\sigma(z) = \\frac{e^z}{1 + e^z}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma <- function(z) exp(z) / (1 + exp(z))\n\ntibble(z = seq(-6, 6, by = 0.05)) |>\n  mutate(prob = sigma(z)) |>\n  ggplot(aes(z, prob)) +\n  geom_line(color = \"#1a9641\", linewidth = 1.3) +\n  geom_hline(yintercept = c(0, 0.5, 1), linetype = \"dashed\", color = \"grey60\") +\n  labs(title = \"The logistic function\",\n       x = \"z (linear combination of predictors)\",\n       y = \"Predicted probability\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](demo_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe idea: let $z = \\beta_0 + \\beta_1 x_1 + \\ldots$ be the linear combination, and then:\n\n$$\\hat{P}(\\text{exit} = 1 \\mid \\mathbf{x}) = \\sigma(z) = \\frac{e^{\\mathbf{X}\\boldsymbol{\\beta}}}{1 + e^{\\mathbf{X}\\boldsymbol{\\beta}}}$$\n\n## From the sigmoid to the logit\n\nRearranging the expression above gives the **logit link**:\n\n$$\\ln\\left(\\frac{P}{1-P}\\right) = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2 + \\ldots$$\n\nThe left-hand side is the **log-odds**. The relationship between probability, odds, and log-odds:\n\n| P(exit) | Odds | Log-odds |\n|---|---|---|\n| 0.10 | 0.11 | −2.20 |\n| 0.25 | 0.33 | −1.10 |\n| 0.50 | 1.00 | 0.00 |\n| 0.75 | 3.00 | 1.10 |\n| 0.90 | 9.00 | 2.20 |\n\n## Maximum likelihood estimation\n\nLogistic regression is not estimated by OLS but by **maximum likelihood estimation (MLE)**. The idea: find the coefficient values β that make the observed data most probable. In practice, R's `glm()` handles this for you.\n\n---\n\n# Logistic Regression in R\n\n## Fitting the model\n\nThe syntax is almost identical to `lm()`. The key difference is `family = binomial`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit_model <- glm(exit ~ sales_log + profit_margin + employees_log,\n                   family = binomial,\n                   data = firms)\n\nsummary(logit_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = exit ~ sales_log + profit_margin + employees_log, \n    family = binomial, data = firms)\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   -1.048479   0.331230  -3.165  0.00155 ** \nsales_log     -0.168696   0.026067  -6.472  9.7e-11 ***\nprofit_margin -1.047630   0.085995 -12.183  < 2e-16 ***\nemployees_log  0.006127   0.043090   0.142  0.88694    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 8810.8  on 17505  degrees of freedom\nResidual deviance: 8333.5  on 17502  degrees of freedom\nAIC: 8341.5\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\nIf you forget `family = binomial`, R will silently fit a Gaussian (OLS) model on your binary outcome. Always check your model specification.\n:::\n\n## Comparing LPM and logit side by side\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"LPM\" = lpm, \"Logit\" = logit_model),\n  stars = TRUE,\n  gof_map = c(\"nobs\", \"r.squared\", \"logLik\", \"AIC\"),\n  title = \"Firm exit: LPM vs. logistic regression\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_lpuqttme3ht4gluveljd(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_lpuqttme3ht4gluveljd\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_lpuqttme3ht4gluveljd');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_lpuqttme3ht4gluveljd(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_lpuqttme3ht4gluveljd\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 11, j: 1 }, { i: 11, j: 2 },  ], css_id: 'tinytable_css_xl2ax7z55o33fymm2wxd',}, \n          { positions: [ { i: 8, j: 2 }, { i: 8, j: 1 },  ], css_id: 'tinytable_css_lj0iemjut84nb0tklhu5',}, \n          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 5, j: 1 }, { i: 6, j: 1 }, { i: 7, j: 1 }, { i: 4, j: 1 }, { i: 9, j: 1 }, { i: 10, j: 1 }, { i: 3, j: 2 }, { i: 9, j: 2 }, { i: 1, j: 2 }, { i: 2, j: 2 }, { i: 7, j: 2 }, { i: 4, j: 2 }, { i: 5, j: 2 }, { i: 6, j: 2 }, { i: 10, j: 2 },  ], css_id: 'tinytable_css_9e0rnibrko8aiq9hhfqh',}, \n          { positions: [ { i: 0, j: 1 }, { i: 0, j: 2 },  ], css_id: 'tinytable_css_i1iwycvv2orkvou2kc0t',}, \n          { positions: [ { i: 11, j: 0 },  ], css_id: 'tinytable_css_f3uxbhqo6r5memsgdhlo',}, \n          { positions: [ { i: 8, j: 0 },  ], css_id: 'tinytable_css_we6fx1wy19rjfdztzcf3',}, \n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 9, j: 0 }, { i: 10, j: 0 },  ], css_id: 'tinytable_css_nx8m0wiqhrfo87eekzki',}, \n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_t9l1u2f8c5pihrp41o6s',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_lpuqttme3ht4gluveljd(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_xl2ax7z55o33fymm2wxd, .table th.tinytable_css_xl2ax7z55o33fymm2wxd { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_lj0iemjut84nb0tklhu5, .table th.tinytable_css_lj0iemjut84nb0tklhu5 { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_9e0rnibrko8aiq9hhfqh, .table th.tinytable_css_9e0rnibrko8aiq9hhfqh { text-align: center; }\n      .table td.tinytable_css_i1iwycvv2orkvou2kc0t, .table th.tinytable_css_i1iwycvv2orkvou2kc0t { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_f3uxbhqo6r5memsgdhlo, .table th.tinytable_css_f3uxbhqo6r5memsgdhlo { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_we6fx1wy19rjfdztzcf3, .table th.tinytable_css_we6fx1wy19rjfdztzcf3 { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_nx8m0wiqhrfo87eekzki, .table th.tinytable_css_nx8m0wiqhrfo87eekzki { text-align: left; }\n      .table td.tinytable_css_t9l1u2f8c5pihrp41o6s, .table th.tinytable_css_t9l1u2f8c5pihrp41o6s { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_lpuqttme3ht4gluveljd\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        <caption>Firm exit: LPM vs. logistic regression</caption>\n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">LPM</th>\n                <th scope=\"col\">Logit</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='3'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>(Intercept)</td>\n                  <td>0.217***</td>\n                  <td>-1.048**</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.022)</td>\n                  <td>(0.331)</td>\n                </tr>\n                <tr>\n                  <td>sales_log</td>\n                  <td>-0.014***</td>\n                  <td>-0.169***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.002)</td>\n                  <td>(0.026)</td>\n                </tr>\n                <tr>\n                  <td>profit_margin</td>\n                  <td>-0.088***</td>\n                  <td>-1.048***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.006)</td>\n                  <td>(0.086)</td>\n                </tr>\n                <tr>\n                  <td>employees_log</td>\n                  <td>0.006*</td>\n                  <td>0.006</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.003)</td>\n                  <td>(0.043)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.</td>\n                  <td>17506</td>\n                  <td>17506</td>\n                </tr>\n                <tr>\n                  <td>R2</td>\n                  <td>0.032</td>\n                  <td></td>\n                </tr>\n                <tr>\n                  <td>Log.Lik.</td>\n                  <td>-556.349</td>\n                  <td>-4166.748</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nNote: the logit model reports log-likelihood and AIC rather than R². These are the relevant goodness-of-fit statistics for maximum likelihood models.\n\n---\n\n# Interpretation\n\n## Level 1: Log-odds (raw coefficients)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(logit_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)     sales_log profit_margin employees_log \n -1.048478951  -0.168695919  -1.047629865   0.006126538 \n```\n\n\n:::\n:::\n\n\nThe coefficient on `profit_margin` is -1.048. \n\nInterpretation: a one-unit increase in `profit_margin` is associated with a change of -1.048 in the *log-odds* of exit. This tells us the **direction** clearly, but the magnitude is not intuitive.\n\n## Level 2: Odds ratios\n\nExponentiate the coefficients to get **odds ratios**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(logit_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)     sales_log profit_margin employees_log \n    0.3504704     0.8447657     0.3507681     1.0061453 \n```\n\n\n:::\n:::\n\n\nThe odds ratio for `profit_margin` is 0.351.\n\nInterpretation: a one-unit increase in profit margin multiplies the odds of exit by 0.351, i.e., it reduces the odds by 64.9%.\n\nWe can add confidence intervals:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(confint(logit_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  2.5 %    97.5 %\n(Intercept)   0.1821600 0.6674216\nsales_log     0.8029502 0.8893463\nprofit_margin 0.2961005 0.4147961\nemployees_log 0.9243338 1.0944416\n```\n\n\n:::\n:::\n\n\n## Level 3: Predicted probabilities (most useful)\n\n### For observed data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirms <- firms |>\n  mutate(pred_prob = predict(logit_model, type = \"response\"))\n\nfirms |>\n  group_by(exit) |>\n  summarise(mean_pred_prob = mean(pred_prob))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n   exit mean_pred_prob\n  <dbl>          <dbl>\n1     0         0.0670\n2     1         0.0994\n```\n\n\n:::\n:::\n\n\nFirms that actually exited had, on average, a predicted exit probability of 0.099, compared to 0.067 for firms that survived. The model is doing something sensible.\n\n### For specific scenarios\n\nThis is often the most useful form for communicating results:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscenarios <- tibble(\n  label         = c(\"Profitable, large\", \"Loss-making, small\"),\n  sales_log     = c(11, 9),\n  employees_log = c(4, 2),\n  profit_margin = c(0.10, -0.15)\n)\n\nscenarios <- scenarios |>\n  mutate(\n    pred_prob = predict(logit_model, newdata = scenarios, type = \"response\")\n  )\n\nscenarios\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  label              sales_log employees_log profit_margin pred_prob\n  <chr>                  <dbl>         <dbl>         <dbl>     <dbl>\n1 Profitable, large         11             4          0.1     0.0481\n2 Loss-making, small         9             2         -0.15    0.0834\n```\n\n\n:::\n:::\n\n\nA profitable, large firm has a predicted exit probability of 0.048, compared to 0.083 for a small, loss-making firm.\n\n### Visualising predicted probabilities\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# How does exit probability vary with profit margin?\ngrid <- tibble(\n  profit_margin = seq(-0.5, 0.5, by = 0.01),\n  sales_log     = mean(firms$sales_log, na.rm = TRUE),\n  employees_log = mean(firms$employees_log, na.rm = TRUE)\n)\n\ngrid <- grid |>\n  mutate(pred_prob = predict(logit_model, newdata = grid, type = \"response\"))\n\nggplot(grid, aes(x = profit_margin, y = pred_prob)) +\n  geom_line(color = \"#1a9641\", linewidth = 1.2) +\n  geom_hline(yintercept = c(0, 1), linetype = \"dashed\", color = \"grey60\") +\n  labs(\n    title = \"Predicted probability of exit vs. profit margin\",\n    subtitle = \"Other variables held at their mean\",\n    x = \"Profit margin\", y = \"P(exit = 1)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](demo_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n## Average Marginal Effects\n\nA cleaner summary of \"the effect of X on P(exit)\" is the **Average Marginal Effect (AME)**. Because logit is non-linear, marginal effects differ across observations. The AME averages them:\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_slopes(logit_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n          Term  Estimate Std. Error       z Pr(>|z|)     S    2.5 %   97.5 %\n employees_log  0.000381    0.00268   0.142    0.887   0.2 -0.00487  0.00563\n profit_margin -0.065177    0.00546 -11.927   <0.001 106.5 -0.07589 -0.05447\n sales_log     -0.010495    0.00163  -6.445   <0.001  33.0 -0.01369 -0.00730\n\nType: response\nComparison: dY/dX\n```\n\n\n:::\n:::\n\n\nThe AME for `profit_margin` tells us: on average across all firms, a one-unit increase in profit margin is associated with a -0.065 change in the probability of exit. This is directly comparable to the LPM coefficient.\n\n\n# Summary\n\n- **OLS on binary outcomes** produces out-of-bounds predictions and invalid standard errors\n- **Logistic regression** uses the sigmoid function to ensure $\\hat{P} \\in [0, 1]$\n- Estimation is via maximum likelihood using `glm(..., family = binomial)`\n- Raw coefficients are in **log-odds space** — hard to interpret directly\n- **Odds ratios** $= e^\\beta$ — easier, but still require explanation\n- **Predicted probabilities** — most useful for business communication; compute with `predict(..., type = \"response\")`\n- **Average marginal effects** via `marginaleffects::avg_slopes()` — a cleaner, directly comparable effect size\n- **Inline R code** ensures your text and numbers stay in sync\n\n---\n\n# Further Reading\n\n- Békés, G. & Kézdi, G. (2021). *Data Analysis for Business, Economics, and Policy*. Ch. 11. Available at [gabors-data-analysis.com](https://gabors-data-analysis.com)\n- James, G., Witten, D., Hastie, T., & Tibshirani, R. (2021). *An Introduction to Statistical Learning*. Ch. 4 (Classification). Available at [statlearning.com](https://www.statlearning.com)\n",
    "supporting": [
      "demo_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}