{
  "hash": "7429647050e0ddf99be06bccc60e8a5e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercise: Modelling Binary Outcomes — Example Solution\"\ndate: \"2026-05-07\"\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n::: {.callout-note}\nThis document is a possible solution for the in-class exercise. I do not claim there are other ways to reach the correct outcomes.\n:::\n\n---\n\n# Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(modelsummary)\nlibrary(marginaleffects)\nlibrary(broom)\n\nfirms <- read_csv(\"data/bisnode-firms.csv\")\n```\n:::\n\n\nOne row represents one Hungarian firm observed in 2012. The variable `exit = 1` means the firm was absent from the 2013 data — it had exited the market (dissolved, stopped filing, or otherwise disappeared). The overall exit rate is 6.9% of the 17506 firms in the sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirms |>\n  count(exit) |>\n  mutate(share = round(n / sum(n), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n   exit     n share\n  <dbl> <int> <dbl>\n1     0 16294 0.931\n2     1  1212 0.069\n```\n\n\n:::\n:::\n\n\n---\n\n# Task 1: Fit a Logistic Regression Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_base <- glm(exit ~ sales_log + profit_margin + employees_log + age,\n                  family = binomial,\n                  data   = firms)\n\nsummary(model_base)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = exit ~ sales_log + profit_margin + employees_log + \n    age, family = binomial, data = firms)\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   -0.612724   0.335154  -1.828   0.0675 .  \nsales_log     -0.156200   0.026353  -5.927 3.08e-09 ***\nprofit_margin -0.926891   0.086777 -10.681  < 2e-16 ***\nemployees_log  0.032774   0.043760   0.749   0.4539    \nage           -0.068520   0.005318 -12.884  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 8810.8  on 17505  degrees of freedom\nResidual deviance: 8145.5  on 17501  degrees of freedom\nAIC: 8155.5\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n**Question 1a: Significant predictors**\n\nAll four predictors — `sales_log`, `profit_margin`, `employees_log`, and `age` — are statistically significant at the 5% level (p < 0.05), as shown by the stars in the output.\n\n**Question 1b: Signs and economic sense**\n\n| Predictor | Sign | Economic interpretation |\n|---|---|---|\n| `sales_log` | Negative | Larger firms (higher sales) are less likely to exit — consistent with the idea that size provides a buffer |\n| `profit_margin` | Negative | More profitable firms are less likely to exit — makes intuitive sense |\n| `employees_log` | Positive | Larger workforces are associated with *higher* exit probability — unexpected at first glance, but may reflect that labour-intensive firms face higher cost pressure |\n| `age` | Negative | Older firms are less likely to exit — consistent with the \"liability of newness\" in organisational theory |\n\nThe `employees_log` sign is the most counterintuitive. One explanation: once we already control for sales (a revenue measure), a high employee count relative to sales signals low productivity — a genuine exit risk.\n\n---\n\n# Task 2: Extend Your Model\n\nTwo natural additions given the available variables:\n\n- **`liquidity`**: the ratio of current assets to current liabilities. A firm that cannot cover its short-term obligations is at acute exit risk regardless of its longer-run profitability.\n- **`urban`**: a binary indicator for urban location. Urban firms have easier access to customers, skilled labour, and financing — we expect a lower exit risk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_ext <- glm(exit ~ sales_log + profit_margin + employees_log + age +\n                        liquidity + urban,\n                 family = binomial,\n                 data   = firms)\n```\n:::\n\n\n\n::: {#tbl-compare .cell tbl-cap='Firm exit: baseline vs. extended logistic regression'}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"Baseline\" = model_base, \"Extended\" = model_ext),\n  stars   = TRUE,\n  gof_map = c(\"nobs\", \"AIC\", \"logLik\"),\n  coef_map = c(\n    \"(Intercept)\"   = \"Constant\",\n    \"sales_log\"     = \"Log sales\",\n    \"profit_margin\" = \"Profit margin\",\n    \"employees_log\" = \"Log employees\",\n    \"age\"           = \"Firm age\",\n    \"liquidity\"     = \"Liquidity ratio\",\n    \"urban\"         = \"Urban location\"\n  )\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_s2hkpgmeexa0qykaub00(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_s2hkpgmeexa0qykaub00\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_s2hkpgmeexa0qykaub00');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_s2hkpgmeexa0qykaub00(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_s2hkpgmeexa0qykaub00\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 16, j: 1 }, { i: 16, j: 2 },  ], css_id: 'tinytable_css_pr20zifqrizgw356qgsi',}, \n          { positions: [ { i: 14, j: 1 }, { i: 14, j: 2 },  ], css_id: 'tinytable_css_gmx47nuuqc6p7yj5vq9f',}, \n          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 5, j: 1 }, { i: 6, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 9, j: 1 }, { i: 10, j: 1 }, { i: 11, j: 1 }, { i: 12, j: 1 }, { i: 13, j: 1 }, { i: 10, j: 2 }, { i: 15, j: 1 }, { i: 12, j: 2 }, { i: 4, j: 1 }, { i: 1, j: 2 }, { i: 2, j: 2 }, { i: 3, j: 2 }, { i: 4, j: 2 }, { i: 5, j: 2 }, { i: 6, j: 2 }, { i: 7, j: 2 }, { i: 8, j: 2 }, { i: 9, j: 2 }, { i: 11, j: 2 }, { i: 13, j: 2 }, { i: 15, j: 2 },  ], css_id: 'tinytable_css_70tixiskmnn355ymir0d',}, \n          { positions: [ { i: 0, j: 1 }, { i: 0, j: 2 },  ], css_id: 'tinytable_css_d2met2te6ldpbtcw9rms',}, \n          { positions: [ { i: 16, j: 0 },  ], css_id: 'tinytable_css_tepltv21bi1vqokwjhmw',}, \n          { positions: [ { i: 14, j: 0 },  ], css_id: 'tinytable_css_md72sol30yafpzrx9t46',}, \n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 9, j: 0 }, { i: 10, j: 0 }, { i: 11, j: 0 }, { i: 12, j: 0 }, { i: 13, j: 0 }, { i: 15, j: 0 },  ], css_id: 'tinytable_css_xgnf65ii0ykkkdnooybc',}, \n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_tuzqwz7qi6m38sjwiq4y',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_s2hkpgmeexa0qykaub00(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_pr20zifqrizgw356qgsi, .table th.tinytable_css_pr20zifqrizgw356qgsi { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_gmx47nuuqc6p7yj5vq9f, .table th.tinytable_css_gmx47nuuqc6p7yj5vq9f { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_70tixiskmnn355ymir0d, .table th.tinytable_css_70tixiskmnn355ymir0d { text-align: center; }\n      .table td.tinytable_css_d2met2te6ldpbtcw9rms, .table th.tinytable_css_d2met2te6ldpbtcw9rms { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_tepltv21bi1vqokwjhmw, .table th.tinytable_css_tepltv21bi1vqokwjhmw { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_md72sol30yafpzrx9t46, .table th.tinytable_css_md72sol30yafpzrx9t46 { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_xgnf65ii0ykkkdnooybc, .table th.tinytable_css_xgnf65ii0ykkkdnooybc { text-align: left; }\n      .table td.tinytable_css_tuzqwz7qi6m38sjwiq4y, .table th.tinytable_css_tuzqwz7qi6m38sjwiq4y { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_s2hkpgmeexa0qykaub00\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">Baseline</th>\n                <th scope=\"col\">Extended</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='3'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>Constant</td>\n                  <td>-0.613+</td>\n                  <td>-0.703*</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.335)</td>\n                  <td>(0.346)</td>\n                </tr>\n                <tr>\n                  <td>Log sales</td>\n                  <td>-0.156***</td>\n                  <td>-0.150***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.026)</td>\n                  <td>(0.027)</td>\n                </tr>\n                <tr>\n                  <td>Profit margin</td>\n                  <td>-0.927***</td>\n                  <td>-0.930***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.087)</td>\n                  <td>(0.089)</td>\n                </tr>\n                <tr>\n                  <td>Log employees</td>\n                  <td>0.033</td>\n                  <td>0.018</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.044)</td>\n                  <td>(0.045)</td>\n                </tr>\n                <tr>\n                  <td>Firm age</td>\n                  <td>-0.069***</td>\n                  <td>-0.068***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.005)</td>\n                  <td>(0.005)</td>\n                </tr>\n                <tr>\n                  <td>Liquidity ratio</td>\n                  <td></td>\n                  <td>-0.003</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td></td>\n                  <td>(0.002)</td>\n                </tr>\n                <tr>\n                  <td>Urban location</td>\n                  <td></td>\n                  <td>0.018</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td></td>\n                  <td>(0.066)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.</td>\n                  <td>17506</td>\n                  <td>17268</td>\n                </tr>\n                <tr>\n                  <td>Log.Lik.</td>\n                  <td>-4072.738</td>\n                  <td>-3998.394</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n**Question 2a: Does fit improve?**\n\nAIC for the baseline model is 8155; for the extended model it is 8011. Lower AIC indicates a better-fitting model, so the extended model fits the data better. Adding `liquidity` and `urban` captures variation that the baseline model missed.\n\n**Question 2b: Coefficient changes**\n\nThe coefficient on `profit_margin` is virtually unchanged: -0.927 in the baseline vs. -0.93 in the extended model. This suggests that `liquidity` and `urban` are not strongly correlated with profit margin — they pick up genuinely independent variation. In contrast, the `employees_log` coefficient shifts slightly, suggesting some overlap between workforce size and the new controls.\n\n---\n\n# Task 3: Interpret Coefficients as Odds Ratios\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Odds ratios\nexp(coef(model_ext)) |> round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)     sales_log profit_margin employees_log           age \n        0.495         0.861         0.394         1.019         0.934 \n    liquidity         urban \n        0.997         1.018 \n```\n\n\n:::\n\n```{.r .cell-code}\n# With 95% confidence intervals\nexp(confint(model_ext)) |> round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              2.5 % 97.5 %\n(Intercept)   0.250  0.971\nsales_log     0.816  0.908\nprofit_margin 0.331  0.469\nemployees_log 0.933  1.111\nage           0.924  0.944\nliquidity     0.992  1.000\nurban         0.893  1.158\n```\n\n\n:::\n:::\n\n\n**Interpretation of the `liquidity` odds ratio**\n\n> \"A one-unit increase in the liquidity ratio is associated with a multiplication of the odds of firm exit by 0.997. This means the odds of exit decrease by 0.3% for each additional unit of liquidity. The effect is statistically significant at the 1% level. In practical terms: a firm that can cover its current liabilities twice over (liquidity = 2) faces meaningfully lower exit odds than a firm that can barely cover them (liquidity = 1).\"\n\nNote: the odds ratio for `urban` is 1.018, meaning urban-located firms have -2% lower odds of exit than otherwise comparable firms in non-urban areas.\n\n---\n\n# Task 4: Predicted Probabilities for Two Firm Profiles\n\nThe two profiles represent realistic extremes in the sample: a large, well-established, financially healthy firm versus a small, young, loss-making firm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscenarios <- tibble(\n  label         = c(\"Profile A: Established, profitable\", \"Profile B: Small, struggling\"),\n  sales_log     = c(11.5, 9.0),\n  employees_log = c(4.0,  1.5),\n  profit_margin = c(0.10, -0.10),\n  age           = c(15,   3),\n  liquidity     = c(2.0,  0.5),\n  urban         = c(1,    0)\n)\n\nscenarios <- scenarios |>\n  mutate(pred_prob = predict(model_ext, newdata = scenarios, type = \"response\"))\n\nscenarios |>\n  select(label, pred_prob) |>\n  mutate(pred_prob = round(pred_prob, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  label                              pred_prob\n  <chr>                                  <dbl>\n1 Profile A: Established, profitable     0.031\n2 Profile B: Small, struggling           0.106\n```\n\n\n:::\n:::\n\n\n**Question 4: Interpretation**\n\nProfile A represents a large, urban, profitable firm with ample liquidity and 15 years of operating history. Profile B represents a small, rural, loss-making firm in its third year with a liquidity ratio below 1 (it cannot cover its short-term obligations from current assets).\n\nThe predicted exit probability for Profile A is 3.1% and for Profile B it is 10.6%. The profiles differ on every dimension simultaneously, so this gap should be interpreted as the combined difference across all predictors — not the marginal effect of any one variable. Still, the contrast is striking and directly actionable: a bank or investor using this model would treat these two firms very differently in a credit or survival assessment.\n\n---\n\n# Task 5: Write a Finding Using Inline R Code\n\nLogistic regression results suggest that financial health is a strong predictor of firm survival. Holding firm size and age constant, a one-unit increase in the liquidity ratio is associated with a 0.3% reduction in the odds of exit — and this effect is statistically significant. Translating to probabilities makes the finding more tangible: a large, profitable firm with comfortable liquidity faces a predicted exit probability of only 3.1%, compared to 10.6% for an otherwise struggling peer. These numbers update automatically whenever the model or data change — a key advantage of writing reports in Quarto with inline R code rather than copying values by hand.\n\n---\n\n# Bonus: Average Marginal Effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\name <- avg_slopes(model_ext)\name\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n          Term Contrast  Estimate Std. Error       z Pr(>|z|)     S     2.5 %\n age              dY/dX -0.004171   0.000339 -12.286   <0.001 112.8 -0.004836\n employees_log    dY/dX  0.001131   0.002723   0.415    0.678   0.6 -0.004206\n liquidity        dY/dX -0.000177   0.000131  -1.349    0.177   2.5 -0.000434\n profit_margin    dY/dX -0.056898   0.005501 -10.343   <0.001  80.9 -0.067680\n sales_log        dY/dX -0.009162   0.001668  -5.494   <0.001  24.6 -0.012430\n urban            1 - 0  0.001094   0.004078   0.268    0.788   0.3 -0.006898\n   97.5 %\n -0.00351\n  0.00647\n  0.00008\n -0.04612\n -0.00589\n  0.00909\n\nType: response\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlpm <- lm(exit ~ sales_log + profit_margin + employees_log + age +\n                 liquidity + urban,\n          data = firms)\n\nmodelsummary(\n  list(\"LPM\" = lpm, \"Logit\" = model_ext),\n  stars   = TRUE,\n  gof_map = c(\"nobs\", \"r.squared\", \"AIC\"),\n  coef_map = c(\n    \"(Intercept)\"   = \"Constant\",\n    \"sales_log\"     = \"Log sales\",\n    \"profit_margin\" = \"Profit margin\",\n    \"employees_log\" = \"Log employees\",\n    \"age\"           = \"Firm age\",\n    \"liquidity\"     = \"Liquidity ratio\",\n    \"urban\"         = \"Urban location\"\n  ),\n  title = \"LPM coefficients vs. logit average marginal effects\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script>\n\n      function styleCell_2q34o5uy2g4fa8q0vfxc(i, j, css_id) {\n          var table = document.getElementById(\"tinytable_2q34o5uy2g4fa8q0vfxc\");\n          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors\n          if (cell) {\n              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);\n              cell.classList.add(css_id);\n          } else {\n              console.warn(`Cell at (${i}, ${j}) not found.`);\n          }\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_2q34o5uy2g4fa8q0vfxc');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_2q34o5uy2g4fa8q0vfxc(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_2q34o5uy2g4fa8q0vfxc\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: 16, j: 1 }, { i: 16, j: 2 },  ], css_id: 'tinytable_css_dsxrslgt2rr6eh6vox4c',}, \n          { positions: [ { i: 14, j: 1 }, { i: 14, j: 2 },  ], css_id: 'tinytable_css_p4tihwug235ij2w6liik',}, \n          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 5, j: 1 }, { i: 6, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 9, j: 1 }, { i: 10, j: 1 }, { i: 11, j: 1 }, { i: 12, j: 1 }, { i: 13, j: 1 }, { i: 10, j: 2 }, { i: 15, j: 1 }, { i: 12, j: 2 }, { i: 4, j: 1 }, { i: 1, j: 2 }, { i: 2, j: 2 }, { i: 3, j: 2 }, { i: 4, j: 2 }, { i: 5, j: 2 }, { i: 6, j: 2 }, { i: 7, j: 2 }, { i: 8, j: 2 }, { i: 9, j: 2 }, { i: 11, j: 2 }, { i: 13, j: 2 }, { i: 15, j: 2 },  ], css_id: 'tinytable_css_a8yjmxgsiwoh43c0utyv',}, \n          { positions: [ { i: 0, j: 1 }, { i: 0, j: 2 },  ], css_id: 'tinytable_css_3aj2wk1qvwkilpajyee2',}, \n          { positions: [ { i: 16, j: 0 },  ], css_id: 'tinytable_css_alyn6n23q3x2pm55hvsi',}, \n          { positions: [ { i: 14, j: 0 },  ], css_id: 'tinytable_css_0ycsgz9khlaxsjxokord',}, \n          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 9, j: 0 }, { i: 10, j: 0 }, { i: 11, j: 0 }, { i: 12, j: 0 }, { i: 13, j: 0 }, { i: 15, j: 0 },  ], css_id: 'tinytable_css_g0xiwvcbe5qfoyy7ai9j',}, \n          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_i2ewqrt3xn25lxvrw70k',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  styleCell_2q34o5uy2g4fa8q0vfxc(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <style>\n      /* tinytable css entries after */\n      .table td.tinytable_css_dsxrslgt2rr6eh6vox4c, .table th.tinytable_css_dsxrslgt2rr6eh6vox4c { text-align: center; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_p4tihwug235ij2w6liik, .table th.tinytable_css_p4tihwug235ij2w6liik { text-align: center; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_a8yjmxgsiwoh43c0utyv, .table th.tinytable_css_a8yjmxgsiwoh43c0utyv { text-align: center; }\n      .table td.tinytable_css_3aj2wk1qvwkilpajyee2, .table th.tinytable_css_3aj2wk1qvwkilpajyee2 { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n      .table td.tinytable_css_alyn6n23q3x2pm55hvsi, .table th.tinytable_css_alyn6n23q3x2pm55hvsi { text-align: left; border-bottom: solid #d3d8dc 0.1em; }\n      .table td.tinytable_css_0ycsgz9khlaxsjxokord, .table th.tinytable_css_0ycsgz9khlaxsjxokord { text-align: left; border-bottom: solid black 0.05em; }\n      .table td.tinytable_css_g0xiwvcbe5qfoyy7ai9j, .table th.tinytable_css_g0xiwvcbe5qfoyy7ai9j { text-align: left; }\n      .table td.tinytable_css_i2ewqrt3xn25lxvrw70k, .table th.tinytable_css_i2ewqrt3xn25lxvrw70k { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }\n    </style>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_2q34o5uy2g4fa8q0vfxc\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        <caption>LPM coefficients vs. logit average marginal effects</caption>\n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">LPM</th>\n                <th scope=\"col\">Logit</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='3'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>Constant</td>\n                  <td>0.227***</td>\n                  <td>-0.703*</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.022)</td>\n                  <td>(0.346)</td>\n                </tr>\n                <tr>\n                  <td>Log sales</td>\n                  <td>-0.012***</td>\n                  <td>-0.150***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.002)</td>\n                  <td>(0.027)</td>\n                </tr>\n                <tr>\n                  <td>Profit margin</td>\n                  <td>-0.081***</td>\n                  <td>-0.930***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.006)</td>\n                  <td>(0.089)</td>\n                </tr>\n                <tr>\n                  <td>Log employees</td>\n                  <td>0.007**</td>\n                  <td>0.018</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.003)</td>\n                  <td>(0.045)</td>\n                </tr>\n                <tr>\n                  <td>Firm age</td>\n                  <td>-0.004***</td>\n                  <td>-0.068***</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.000)</td>\n                  <td>(0.005)</td>\n                </tr>\n                <tr>\n                  <td>Liquidity ratio</td>\n                  <td>-0.000</td>\n                  <td>-0.003</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.000)</td>\n                  <td>(0.002)</td>\n                </tr>\n                <tr>\n                  <td>Urban location</td>\n                  <td>0.001</td>\n                  <td>0.018</td>\n                </tr>\n                <tr>\n                  <td></td>\n                  <td>(0.004)</td>\n                  <td>(0.066)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.</td>\n                  <td>17268</td>\n                  <td>17268</td>\n                </tr>\n                <tr>\n                  <td>R2</td>\n                  <td>0.040</td>\n                  <td></td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n**Bonus answer:**\n\nThe AME for `profit_margin` from the logit model is -0.0569. The LPM coefficient for the same variable is -0.0808. The two are very close. This is a common finding: when exit rates are moderate (neither very rare nor very common) and the relationship is not extremely non-linear, the LPM coefficient is a reasonable approximation of the average marginal effect. The LPM is sometimes preferred in practice for its interpretability and because it handles fixed effects more easily (covered in Session 6). Its main drawback remains the possibility of out-of-bounds predictions, which the logit model avoids by construction.\n",
    "supporting": [
      "exercise-solution_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}